export const data = [
  {
    _id: '6055d8308a41c8a59b7e1db7',
    index: 0,
    guid: '96fb5b49-5210-4b92-bc70-4fbbf0fabaf9',
    isActive: true,
    balance: '$1,629.57',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'blue',
    name: {
      first: 'Daniels',
      last: 'Montgomery',
    },
    company: 'XELEGYL',
    email: 'daniels.montgomery@xelegyl.name',
    phone: '+1 (834) 481-3474',
    address: '899 Baycliff Terrace, Cloverdale, Massachusetts, 6055',
    about:
      'Ullamco velit occaecat quis mollit eiusmod cillum fugiat velit velit id fugiat. Ipsum ullamco voluptate cillum occaecat tempor incididunt anim aute veniam non dolor. Officia proident pariatur dolore culpa velit deserunt do tempor occaecat esse anim duis. Mollit elit eu proident sunt cillum aliquip qui voluptate elit culpa dolore. Ad adipisicing et ut eu qui in id.',
    registered: 'Friday, October 12, 2018 2:11 PM',
    latitude: '38.430767',
    longitude: '57.347327',
    tags: ['proident', 'minim', 'eu', 'veniam', 'adipisicing'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Graham Nolan',
      },
      {
        id: 1,
        name: 'Stevens Albert',
      },
      {
        id: 2,
        name: 'Conley Hampton',
      },
    ],
    greeting: 'Hello, Daniels! You have 6 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6055d830ac51d00dae06a21f',
    index: 1,
    guid: 'aec54af7-ce6a-4563-bbbe-c0ae307cb3dd',
    isActive: true,
    balance: '$2,410.24',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'brown',
    name: {
      first: 'Mcleod',
      last: 'Duran',
    },
    company: 'POLARIA',
    email: 'mcleod.duran@polaria.tv',
    phone: '+1 (893) 567-2144',
    address: '964 Highland Boulevard, Delco, District Of Columbia, 9147',
    about:
      'Culpa est aliquip labore duis nisi magna consequat culpa commodo do aliqua consectetur ipsum tempor. Incididunt elit cupidatat et quis exercitation veniam aute. Esse est ex adipisicing commodo eu anim aute deserunt. Ex laborum adipisicing nulla do dolore duis consectetur Lorem consequat sint est veniam. Est pariatur exercitation exercitation nisi velit elit culpa enim aliquip commodo ullamco culpa. Est ad adipisicing culpa in consequat quis occaecat.',
    registered: 'Monday, July 20, 2015 4:08 AM',
    latitude: '24.064271',
    longitude: '122.270125',
    tags: ['consectetur', 'eiusmod', 'voluptate', 'ex', 'duis'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Elisa Ayala',
      },
      {
        id: 1,
        name: 'Calderon Fleming',
      },
      {
        id: 2,
        name: 'Savannah Haley',
      },
    ],
    greeting: 'Hello, Mcleod! You have 9 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6055d8308f02b4838badad36',
    index: 2,
    guid: 'd9cbac57-9920-4a53-97a4-5023f716d171',
    isActive: false,
    balance: '$3,428.81',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'blue',
    name: {
      first: 'Workman',
      last: 'Joseph',
    },
    company: 'NETPLAX',
    email: 'workman.joseph@netplax.io',
    phone: '+1 (959) 558-3176',
    address: '821 Highland Avenue, Fowlerville, Florida, 3695',
    about:
      'Do aute sit non non nostrud voluptate culpa tempor. Veniam velit do tempor culpa in velit sint culpa non ullamco. Sunt ipsum duis Lorem fugiat deserunt est cupidatat est deserunt nulla exercitation non velit ullamco.',
    registered: 'Friday, March 24, 2017 5:35 AM',
    latitude: '38.93241',
    longitude: '162.034063',
    tags: ['dolor', 'quis', 'aliqua', 'nostrud', 'eiusmod'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Roberta Powers',
      },
      {
        id: 1,
        name: 'Cooley Mueller',
      },
      {
        id: 2,
        name: 'Sampson Greene',
      },
    ],
    greeting: 'Hello, Workman! You have 8 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6055d83085219f8e5a6ad4d6',
    index: 3,
    guid: 'beb471e8-4d2a-4665-a896-df1e5f1c3b9e',
    isActive: true,
    balance: '$1,825.39',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'brown',
    name: {
      first: 'Beryl',
      last: 'Bolton',
    },
    company: 'ISBOL',
    email: 'beryl.bolton@isbol.org',
    phone: '+1 (936) 554-2984',
    address: '847 Merit Court, Grenelefe, Arizona, 8933',
    about:
      'Ad ut tempor dolore nostrud deserunt. Adipisicing sint fugiat sit non deserunt est dolor. Eu eiusmod irure irure tempor pariatur duis Lorem fugiat sit reprehenderit excepteur laboris sint. Laborum reprehenderit sit esse fugiat dolor incididunt fugiat sint ea. Ipsum et anim nostrud officia. Officia eiusmod ad dolore officia dolor fugiat esse Lorem sunt minim tempor.',
    registered: 'Monday, February 11, 2019 11:44 PM',
    latitude: '-15.724899',
    longitude: '7.783928',
    tags: ['incididunt', 'ea', 'est', 'consequat', 'cillum'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Sawyer Sparks',
      },
      {
        id: 1,
        name: 'Velma Sloan',
      },
      {
        id: 2,
        name: 'Schmidt Acosta',
      },
    ],
    greeting: 'Hello, Beryl! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '6055d830fdcfa0a7bd683dca',
    index: 4,
    guid: '1750bc55-1bff-42c7-a06f-c2e1c809d99b',
    isActive: false,
    balance: '$1,743.45',
    picture: 'http://placehold.it/32x32',
    age: 29,
    eyeColor: 'green',
    name: {
      first: 'Jenifer',
      last: 'Camacho',
    },
    company: 'CUIZINE',
    email: 'jenifer.camacho@cuizine.com',
    phone: '+1 (897) 431-2529',
    address: '263 Campus Place, Blanco, Missouri, 1011',
    about:
      'Mollit laboris culpa pariatur duis aute magna adipisicing ex adipisicing Lorem. Magna adipisicing deserunt eiusmod nulla ad. Eiusmod pariatur occaecat elit Lorem magna. Duis exercitation labore officia sunt. Labore quis aute adipisicing minim proident dolor et esse veniam id. Exercitation in et dolore duis esse dolor.',
    registered: 'Wednesday, February 28, 2018 5:37 PM',
    latitude: '-5.331702',
    longitude: '-107.026549',
    tags: ['fugiat', 'irure', 'nulla', 'reprehenderit', 'occaecat'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Blackburn Anderson',
      },
      {
        id: 1,
        name: 'Gilbert Silva',
      },
      {
        id: 2,
        name: 'Kimberly Neal',
      },
    ],
    greeting: 'Hello, Jenifer! You have 6 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6055d8305d5694c29c70147c',
    index: 5,
    guid: 'bc0cea8b-ad41-4c7e-9527-301b92c659a0',
    isActive: false,
    balance: '$2,697.47',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'green',
    name: {
      first: 'Lucile',
      last: 'Jimenez',
    },
    company: 'INTERODEO',
    email: 'lucile.jimenez@interodeo.net',
    phone: '+1 (998) 522-3240',
    address: '180 McClancy Place, Condon, Delaware, 284',
    about:
      'Non nisi consectetur qui occaecat cillum. Id aliquip amet minim duis cillum qui. Est proident ex dolore amet minim exercitation. Aute officia laboris amet quis consectetur. Nulla duis quis excepteur minim aute ipsum ullamco id sit excepteur. Sint ullamco officia eiusmod anim excepteur sint quis laboris adipisicing.',
    registered: 'Friday, July 18, 2014 6:06 PM',
    latitude: '-73.13856',
    longitude: '112.27136',
    tags: ['dolor', 'enim', 'minim', 'cillum', 'ad'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Hensley Kent',
      },
      {
        id: 1,
        name: 'Brenda Glover',
      },
      {
        id: 2,
        name: 'Gladys Sharp',
      },
    ],
    greeting: 'Hello, Lucile! You have 5 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '6055d830079be0f8018e0099',
    index: 6,
    guid: 'd62bf746-5e78-438d-9358-d2b6808b70f4',
    isActive: false,
    balance: '$1,462.47',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'green',
    name: {
      first: 'Marcia',
      last: 'Brennan',
    },
    company: 'ZOARERE',
    email: 'marcia.brennan@zoarere.me',
    phone: '+1 (972) 559-2675',
    address: '832 Heyward Street, Brownlee, Montana, 1349',
    about:
      'Cupidatat mollit cillum qui mollit proident reprehenderit. Proident enim occaecat consequat officia incididunt ea exercitation pariatur ex irure. Cillum deserunt nulla amet ex aliquip minim aute cupidatat esse sint. Id ullamco occaecat Lorem ad pariatur cillum fugiat consectetur aliquip qui laboris amet ad reprehenderit. Velit dolor laborum nisi aute. Enim culpa ut incididunt adipisicing. Consequat ea commodo ut laboris cillum tempor.',
    registered: 'Monday, September 29, 2014 2:34 PM',
    latitude: '-14.24394',
    longitude: '23.483622',
    tags: ['esse', 'proident', 'voluptate', 'deserunt', 'ullamco'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Hatfield Koch',
      },
      {
        id: 1,
        name: 'Janice Lloyd',
      },
      {
        id: 2,
        name: 'Ruth Preston',
      },
    ],
    greeting: 'Hello, Marcia! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6055d8302952472a67bddad8',
    index: 7,
    guid: 'e7e37fdf-7349-469c-9004-b1e2c3b2d21f',
    isActive: true,
    balance: '$3,241.37',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'brown',
    name: {
      first: 'Goldie',
      last: 'Shepard',
    },
    company: 'TECHADE',
    email: 'goldie.shepard@techade.info',
    phone: '+1 (911) 556-3736',
    address: '118 Conway Street, Jugtown, Oklahoma, 8695',
    about:
      'Cupidatat duis labore sint laborum nulla officia fugiat nisi. Amet ipsum non qui consectetur do fugiat eu duis dolore anim. Pariatur elit elit aliquip ex labore ullamco laboris amet exercitation in fugiat. Deserunt voluptate mollit ipsum dolore nisi tempor ipsum incididunt. Ipsum excepteur incididunt pariatur velit ex qui sunt minim dolor ut sit ea occaecat velit. Quis nostrud nulla commodo consectetur veniam ipsum ullamco in esse ex dolor sit.',
    registered: 'Tuesday, May 8, 2018 7:40 PM',
    latitude: '-10.642216',
    longitude: '-170.251441',
    tags: ['proident', 'tempor', 'Lorem', 'ex', 'quis'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Sandy Hensley',
      },
      {
        id: 1,
        name: 'Cassie Harrell',
      },
      {
        id: 2,
        name: 'Helene Franks',
      },
    ],
    greeting: 'Hello, Goldie! You have 8 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '6055d8302ae611ec5f79581f',
    index: 8,
    guid: '5518bc23-064a-4241-a3a5-386326b39176',
    isActive: true,
    balance: '$2,153.85',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'green',
    name: {
      first: 'Thelma',
      last: 'Flynn',
    },
    company: 'ISOSURE',
    email: 'thelma.flynn@isosure.ca',
    phone: '+1 (875) 433-3698',
    address: '819 Himrod Street, Fontanelle, Puerto Rico, 2462',
    about:
      'Veniam ut sit et ipsum. Dolore veniam fugiat laboris laborum pariatur magna irure Lorem tempor nulla esse. In aliqua in sit amet anim.',
    registered: 'Monday, December 29, 2014 5:07 PM',
    latitude: '-74.747948',
    longitude: '-94.953769',
    tags: ['deserunt', 'do', 'non', 'veniam', 'Lorem'],
    range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    friends: [
      {
        id: 0,
        name: 'Amie Young',
      },
      {
        id: 1,
        name: 'Dennis Barry',
      },
      {
        id: 2,
        name: 'Murray Kinney',
      },
    ],
    greeting: 'Hello, Thelma! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
];
